routes/web.php
<?php

use App\Http\Controllers\customer\RobotController;
use App\Http\Controllers\Dev\MutationController as DevMutationController;
use App\Http\Controllers\Dev\UserController as DevUserController;
use App\Http\Controllers\Dev\BankController as DevBankController;
use App\Http\Controllers\Dev\LevelController as DevLevelController;
use App\Http\Controllers\Dev\RobotController as DevRobotController;
use App\Http\Controllers\Dev\KursController as DevKursController;
use App\Http\Controllers\Dev\ContactController as DevContactController;
use App\Http\Controllers\Dev\TopupController as DevTopupController;
use App\Http\Controllers\Dev\MemberBankController as DevMemberBankController;
use App\Http\Controllers\Dev\MemberController as DevMemberController;
use App\Http\Controllers\Dev\AkunMT5Controller as DevAkunMT5Controller;
use App\Http\Controllers\Dev\WithdrawController as DevWithdrawController;
use App\Http\Controllers\Dev\ActivationaccountController as DevActivationaccountController;
use App\Http\Controllers\Dev\versionapp\VersionController as DevVersionController;
use App\Http\Controllers\Dev\BypassController as DevBypassController;
use App\Http\Controllers\Dev\NetworkController as DevNetworkController;
use App\Http\Controllers\Dev\KeuntunganController as DevKeuntunganController;
//Customer
use App\Http\Controllers\Customer\robot\RobotController as CustomerRobotController;
use App\Http\Controllers\Customer\robot\BeliRobotController as CustomerBeliRobotController;
use App\Http\Controllers\Customer\profile\ProfileController as CustomerProfileController;

//cashier
use App\Http\Controllers\Cashier\masterdata\UserController as CashierUserController;
use App\Http\Controllers\Cashier\topup\TopupController as CashierTopupController;
use App\Http\Controllers\Cashier\WithdrawController as CashierWithdrawController;
use App\Http\Controllers\Cashier\keuntungan\KeuntunganController as CashierKeuntunganController;
use App\Http\Controllers\Cashier\manajemenuser\AkunMT5Controller as CashierAkunMT5Controller;
use App\Http\Controllers\Cashier\ActivationaccountController as CashierActivationaccountController;
use App\Http\Controllers\Cashier\TopupController as CashierTopup2Controller;
use App\Http\Controllers\Cashier\mutasi\MutasiController as CashierMutasiController;
use App\Http\Controllers\Dev\TRC20\TRC20Controller;
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
})->middleware(['guest']);


Route::get('/csrf', function () {
    return csrf_token();
});


Route::get('/coomingsoon', function () {
    return view('coomingsoon');
})->name('cooming');

Route::get('/home', function () {
    Session::put('menu', 'home');
    return redirect('/dashboard/home');
});

Route::webhooks('webhook-moota-url');

Route::name('dashboard.')->prefix('dashboard')->middleware(['auth'])->group(function () {
    Route::get('/home', function () {
        return view('page.dashboard.index');
    });
    Route::name('dev.')->prefix('dev')->middleware(['role:Dev'])->group(function () {
        //mutasi
        Route::get('/mutasi', [DevMutationController::class, 'index'])->name('mutasi.index');
        Route::post('/mutasi/cek', [DevMutationController::class, 'find'])->name('mutasi.index.find');
        Route::post('/mutasi/usercek', [DevMutationController::class, 'usercek'])->name('mutasi.index.usercek');
        Route::post('/mutasi/store', [DevMutationController::class, 'store'])->name('mutasi.index.store');
        Route::get('/mutasi/history', [DevMutationController::class, 'history'])->name('mutasi.index.history');

        //activation Account
        Route::get('/activation-account', [DevActivationaccountController::class, 'index'])->name('activation-account.index');
        Route::get('/activation-account/approval', [DevActivationaccountController::class, 'approval'])->name('activation-account.approval');
        Route::get('/activation-account/approve{id}', [DevActivationaccountController::class, 'approve'])->name('activation-account.approve');

        //user
        Route::get('/user', [DevUserController::class, 'index'])->name('user.index');
        Route::get('/user/create', [DevUserController::class, 'create'])->name('user.create');
        Route::post('/user/store', [DevUserController::class, 'store'])->name('user.store');
        Route::post('/user/update', [DevUserController::class, 'update'])->name('user.update');
        Route::get('/user/delete{id}', [DevUserController::class, 'destroy'])->name('user.delete');
        Route::post('/user/profil', [DevUserController::class, 'profil'])->name('user.profil');
        Route::post('/user/password', [DevUserController::class, 'password'])->name('user.password');
        //member
        Route::get('/member', [DevMemberController::class, 'index'])->name('member.index');;
        Route::post('/member/store', [DevMemberController::class, 'store'])->name('member.store');
        Route::post('/member/update', [DevMemberController::class, 'update'])->name('member.update');
        Route::get('/member/delete{id}', [DevMemberController::class, 'destroy'])->name('member.delete');
        //akunMT5
        Route::get('/akunmt5', [DevAkunMT5Controller::class, 'index'])->name('akunmt5.index');
        Route::post('/akunmt5/store', [DevAkunMT5Controller::class, 'store'])->name('akunmt5.store');
        Route::post('/akunmt5/update', [DevAkunMT5Controller::class, 'update'])->name('akunmt5.update');
        //Bank
        Route::get('/bank', [DevBankController::class, 'index'])->name('bank.index');
        Route::post('/bank/store', [DevBankController::class, 'store'])->name('bank.store');
        Route::post('/bank/update', [DevBankController::class, 'update'])->name('bank.update');
        Route::get('/bank/delete{id}', [DevBankController::class, 'destroy'])->name('bank.delete');

        //level
        Route::get('/level', [DevLevelController::class, 'index'])->name('level.index');
        Route::post('/level/store', [DevLevelController::class, 'store'])->name('level.store');
        Route::post('/level/update', [DevLevelController::class, 'update'])->name('level.update');
        Route::get('/level/delete{id}', [DevLevelController::class, 'destroy'])->name('level.delete');
        //level
        Route::get('/robot', [DevRobotController::class, 'index'])->name('robot.index');
        Route::post('/robot/store', [DevRobotController::class, 'store'])->name('robot.store');
        Route::post('/robot/update', [DevRobotController::class, 'update'])->name('robot.update');
        Route::get('/robot/delete{id}', [DevRobotController::class, 'destroy'])->name('robot.delete');

        //Kurs
        Route::get('/kurs', [DevKursController::class, 'index'])->name('kurs.index');
        Route::post('/kurs/store', [DevKursController::class, 'store'])->name('kurs.store');
        Route::post('/kurs/update', [DevKursController::class, 'update'])->name('kurs.update');
        Route::get('/kurs/delete{id}', [DevKursController::class, 'destroy'])->name('kurs.delete');

        //Contact
        Route::post('/contact/update', [DevContactController::class, 'update'])->name('contact.update');
        Route::get('/contact', [DevContactController::class, 'index'])->name('contact.index');

        //Topup
        Route::get('/topup', [DevTopupController::class, 'index'])->name('topup.index');
        Route::get('/topup/approval', [DevTopupController::class, 'approval'])->name('topup.approval');
        Route::post('/topup/approve', [DevTopupController::class, 'approve'])->name('topup.approve');
        Route::get('/topupmt5/', [DevTopupController::class, 'indexmt5'])->name('topupmt5.index');
        Route::post('/topupmt5/tambah', [DevTopupController::class, 'tambah'])->name('topupmt5.tambah');
        Route::post('/topupmt5/tambahmodal', [DevTopupController::class, 'tambahmodal'])->name('topupmt5.tambahmodal');
        // Route::get('/topupmt5/kurang', [DevTopupController::class, 'tambah'])->name('topup.approve');
        // Route::post('/topupmt5/kurang{id}', [DevTopupController::class, 'approve'])->name('topup.approve');

        //WD
        Route::get('/withdraw', [DevWithdrawController::class, 'index'])->name('withdraw.index');
        Route::get('/withdraw/approval', [DevWithdrawController::class, 'approval'])->name('withdraw.approval');
        Route::post('/withdraw/approve', [DevWithdrawController::class, 'approve'])->name('withdraw.approve');

        //u=member bank
        Route::get('/member-bank', [DevMemberBankController::class, 'index'])->name('member-bank.index');
        Route::post('/member-bank/store', [DevMemberBankController::class, 'store'])->name('member-bank.store');
        Route::post('/member-bank/update', [DevMemberBankController::class, 'update'])->name('member-bank.update');
        Route::get('/member-bank/delete{id}', [DevMemberBankController::class, 'destroy'])->name('member-bank.delete');

        //version app
        Route::get('version-app', [DevVersionController::class, 'index'])->name('version.index');
        Route::post('version-app', [DevVersionController::class, 'store'])->name('version.store');

        //bypass robot
        Route::get('bypassrobot', [DevBypassController::class, 'index'])->name('bypassrobot.index');

        //networkt
        Route::get('network', [DevNetworkController::class, 'index'])->name('network.index');

        //keuntungan MT5

        Route::resources([
            'keuntungan' => DevKeuntunganController::class,
        ]);

app/Models/Topup.php
<?php

namespace App\Models;

use DateTimeInterface;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Topup extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $table = 'topups';

    protected $fillable = [
        'user_id',
        'bank_id',
        'amount',
        'unik',
        'status',
        'image_id',
    ];

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }

    public function status()
    {
        return $this->belongsTo(Status::class, 'status', 'id');
    }

    public function bank()
    {
        return $this->belongsTo(Tabelbank::class, 'bank_id', 'id');
    }
}

app/Http/Controllers/Cashier/topup/TopupController.php
<?php

namespace App\Http\Controllers\Cashier\topup;

use App\Helper\LevelUserHelper;
use App\Http\Controllers\Controller;
use App\Models\Kurs;
use App\Models\Topup;
use App\Models\User;
use App\Models\Walletmt5;
use App\Models\Walletmt5history;
use Illuminate\Auth\Events\Validated;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;
use DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Carbon;
use Illuminate\Support\Str;




class TopupController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */


    public function indexmt5()
    {
        $selectmt5 = User::role('Customer')->with(['mt5'])->get();
        // $selectmt5 = DB::SELECT("select * from walletmt5s a, users b where a.user_id=b.id;");

        // dd($selectmt5);
        return view('page.dashboard.cashier.topup.topupmt5.index', compact(['selectmt5']));
    }

    public function tambah(Request $request)
    {
        $usrid = $request->id;
        $balance = $request->balance;
        $idwal = $request->idb;
        $idmt5 = DB::select("select id from walletmt5s where user_id=$usrid");
        $balanceawal = DB::select("select balance from walletmt5s where user_id=$usrid");
        $balanceawalmodal = DB::select("select modal_user from users where id=$usrid");


        $wallet = DB::table('walletmt5s')->where('user_id', $usrid)->update([
            'balance' => $balanceawal[0]->balance + (int)$balance,
            'last_update' => Carbon::now(),
            'last_token' => Str::random(60),
        ]);

        $mu = DB::table('users')->where('id', $usrid)->update([
            'modal_user' => $balanceawalmodal[0]->modal_user + (int)$balance,
            'updated_at' => Carbon::now(),
        ]);


        $data = Walletmt5history::create([
            'user_id' => $usrid,
            'wallet_id' => (int)$idmt5,
            'hystory_type_id' => '4',
            'time' => Carbon::now(),
            'note' => 'Admin topupmt5',
            'amount' => $balance,
            'status' => '15',
            'token' => Str::random(60),
        ]);


        return redirect()->route('dashboard.cashier.topup.topupmt5.index')->with('berhasil', '.');
    }

    public function tambahmodal(Request $request)
    {
        $usrid = $request->id;
        // dd($balanceawalmodal[0]->modal_user);
        $modalrp = $request->modalrupiah;
        $modaldl = $request->modal;
        $getkurs = Kurs::find(1)->harga_jual;
        $hasil = round($modalrp / $getkurs, 2);

        if ($request->modalrupiah) {
            $mu = DB::table('users')->where('id', $usrid)->update([
                'modal_user' => $hasil,
                'updated_at' => Carbon::now(),
            ]);
        } else {
            $mu = DB::table('users')->where('id', $usrid)->update([
                'modal_user' => $modaldl,
                'updated_at' => Carbon::now(),
            ]);
        }


        return redirect()->route('dashboard.cashier.topup.topupmt5.index')->with('berhasil', '.');
    }
}

resources/views/page/dashboard/dev/topup/topupmt5/index.blade.php
@extends('layouts.dash')
<title>Dashboard | Manajemen User</title>
@section('content')
     <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
        Saldo MT5
        <!-- <small>advanced tables</small> -->
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li><a href="#">Topup</a></li>
        <li class="active">Saldo MT5</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      @php if(Session::get('berhasilupdate')){ @endphp
      <div class="alert alert-warning" >
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
                     Data Berhasil diupdate
      </div> @php } @endphp
      @php if(Session::get('gagal')){ @endphp
      <div class="alert alert-danger" >
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
                     Email sudah pernah terdaftar
      </div> @php } @endphp
      @php if(Session::get('berhasil')){ @endphp
      <div class="alert alert-success" >
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
                     Data Berhasil ditambahkan
      </div> @php } @endphp
      @php if(Session::get('hapus')){ @endphp
      <div class="alert alert-danger" >
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
                     Data Berhasil dihapus
      </div> @php } @endphp

      <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">Top Up MT5</h3>
              <span class="input-group-btn">
                <a data-toggle="modal" data-target="#modal-tambah"><buttonid="search-btn" class="btn btn-primary"><i class="fa fa-plus"></i>
                </button>Tambah Topup MT5</a>
                <a data-toggle="modal" data-target="#modal-tambahmodal" style="margin-left: 13px"><buttonid="search-btn" class="btn btn-primary"><i class="fa fa-plus"></i>
                </button>Tambah Modal User</a>
              </span>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="table1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>#</th>
                  <th>Nama</th>
                  <th>Saldo MT5</th>
                  <th>Modal User</th>
                  <th>Last Uptade</th>
                </tr>
                </thead>
                <tbody>
                @php
                    $i = 1 ;
                @endphp
                @foreach ($selectmt5 as $dt)
                <tr>
                  <td>{{$i++}}</td>
                  <td>{{$dt->name}}</td>
                  <td>{{$dt->balance}}</td>
                  <td>{{$dt->modal_user}}</td>
                  <td>{{$dt->last_update}}</td>
                </tr>
                @endforeach
                </tbody>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
<!--
      Modal -->


      <div class="modal fade" id="modal-tambah" role="dialog">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title">Tambah Topup MT5</h4>
            </div>
            <div class="modal-body">

             <form class="form-horizontal" action="{{ route('dashboard.dev.topupmt5.tambah') }}" method="post">
            @csrf
              <div class="box-body">

                <div class="form-group">
                  <label for="id" class="col-sm-2 control-label">Nama User</label>
                  <div class="col-sm-10">
                    @php
                    $data = DB::select("select * from users");
                    @endphp
                    <select class="form-control select2" name="id" id="id" style="width: 100%;">
                      @foreach ($data as $dt)
                      <option value="{{$dt->id}}">{{$dt->name}}</option>

                      @endforeach
                    </select>
                  </div>
                </div>

                <div class="form-group">
                    <label for="nama" class="col-sm-2 control-label">Balance</label>
                    <div class="col-sm-10">
                      <input type="" class="form-control" id="balance" name="balance" placeholder="100" required="" >
                    </div>
                  </div>
              </div>
              <!-- /.box-body -->
              <div class="box-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Batal</button>
                <button type="submit" class="btn btn-primary">Simpan</button>
              </div>
              <!-- /.box-footer -->
            </form>
            </div>
          </div>
          <!-- /.modal-content -->
        </div>
      </div>
  <div class="modal fade" id="modal-tambahmodal" role="dialog">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title">Tambah Modal User</h4>
            </div>
            <div class="modal-body">

             <form class="form-horizontal" action="{{ route('dashboard.dev.topupmt5.tambahmodal') }}" method="post">
            @csrf
              <div class="box-body">

                <div class="form-group">
                  <label for="id" class="col-sm-2 control-label">Nama Member</label>
                  <div class="col-sm-10" style="margin-top: 12px">
                    @php
                    $data = DB::select("select * from users");
                    @endphp
                    <select class="form-control select2" name="id" id="id" style="width: 100%;">
                      @foreach ($data as $dt)
                      <option value="{{$dt->id}}">{{$dt->name}}</option>
                      @endforeach
                    </select>
                  </div>
                </div>
                <div class="nav-tabs-custom">
                    <ul class="nav nav-tabs">
                      <li class="active"><a href="#tab_1" data-toggle="tab">USD</a></li>
                      <li><a href="#tab_2" data-toggle="tab">IDR</a></li>
                    </ul>
                    <div class="tab-content">
                      <div class="tab-pane active" id="tab_1">
                        <div class="form-group">
                            <label for="modal" class="col-sm-2 control-label">Modal User (USD)</label>
                            <div class="col-sm-10">
                              <input type="number" step="0.01" class="form-control" id="modal" name="modal" placeholder="100" style="margin-top: 18px">
                            </div>
                        </div>
                      </div>
                      <!-- /.tab-pane -->
                      <div class="tab-pane" id="tab_2">
                        <div class="form-group">
                            <label for="modalrupiah" class="col-sm-2 control-label">Modal User (IDR)</label>
                            <div class="col-sm-10">
                              <input type="number" class="form-control" id="modalrupiah" name="modalrupiah" placeholder="100" style="margin-top: 18px">
                            </div>
                        </div>
                      </div>

                    </div>
                    <!-- /.tab-content -->
                  </div>


              </div>
              <!-- /.box-body -->
              <div class="box-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Batal</button>
                <button type="submit" class="btn btn-primary">Simpan</button>
              </div>
              <!-- /.box-footer -->
            </form>
            </div>
          </div>
          <!-- /.modal-content -->
        </div>
      </div>
    </section>
    <!-- /.content -->
    <!-- DataTables -->

@endsection
@section('scripts')
    <script src="{{asset('assets/AdminLTE/bower_components/datatables.net/js/jquery.dataTables.min.js')}}"></script>

    <script src="{{asset('assets/AdminLTE/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>

    <script>
      $(function () {
        $('#table1').DataTable({
          'paging'      : true,
          'lengthChange': true,
          'searching'   : true,
          'ordering'    : true,
          'info'        : true,
          'autoWidth'   : true
        })
        $('#table2').DataTable({
          'paging'      : true,
          'lengthChange': true,
          'searching'   : true,
          'ordering'    : true,
          'info'        : true,
          'autoWidth'   : true
        })
      })
    </script>
    <script>
        $(function () {
        //Initialize Select2 Elements
        $('.select2').select2()
        })
    </script>
    <script src="{{asset('assets/AdminLTE/bower_components/select2/dist/js/select2.full.min.js')}}"></script>

@endsection