routes/web.php
<?php

use App\Http\Controllers\customer\RobotController;
use App\Http\Controllers\Dev\MutationController as DevMutationController;
use App\Http\Controllers\Dev\UserController as DevUserController;
use App\Http\Controllers\Dev\BankController as DevBankController;
use App\Http\Controllers\Dev\LevelController as DevLevelController;
use App\Http\Controllers\Dev\RobotController as DevRobotController;
use App\Http\Controllers\Dev\KursController as DevKursController;
use App\Http\Controllers\Dev\ContactController as DevContactController;
use App\Http\Controllers\Dev\TopupController as DevTopupController;
use App\Http\Controllers\Dev\MemberBankController as DevMemberBankController;
use App\Http\Controllers\Dev\MemberController as DevMemberController;
use App\Http\Controllers\Dev\AkunMT5Controller as DevAkunMT5Controller;
use App\Http\Controllers\Dev\WithdrawController as DevWithdrawController;
use App\Http\Controllers\Dev\ActivationaccountController as DevActivationaccountController;
use App\Http\Controllers\Dev\versionapp\VersionController as DevVersionController;
use App\Http\Controllers\Dev\BypassController as DevBypassController;
use App\Http\Controllers\Dev\NetworkController as DevNetworkController;
use App\Http\Controllers\Dev\KeuntunganController as DevKeuntunganController;
//Customer
use App\Http\Controllers\Customer\robot\RobotController as CustomerRobotController;
use App\Http\Controllers\Customer\robot\BeliRobotController as CustomerBeliRobotController;
use App\Http\Controllers\Customer\profile\ProfileController as CustomerProfileController;

//cashier
use App\Http\Controllers\Cashier\masterdata\UserController as CashierUserController;
use App\Http\Controllers\Cashier\topup\TopupController as CashierTopupController;
use App\Http\Controllers\Cashier\WithdrawController as CashierWithdrawController;
use App\Http\Controllers\Cashier\keuntungan\KeuntunganController as CashierKeuntunganController;
use App\Http\Controllers\Cashier\manajemenuser\AkunMT5Controller as CashierAkunMT5Controller;
use App\Http\Controllers\Cashier\ActivationaccountController as CashierActivationaccountController;
use App\Http\Controllers\Cashier\TopupController as CashierTopup2Controller;
use App\Http\Controllers\Cashier\mutasi\MutasiController as CashierMutasiController;
use App\Http\Controllers\Dev\TRC20\TRC20Controller;
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
})->middleware(['guest']);


Route::get('/csrf', function () {
    return csrf_token();
});


Route::get('/coomingsoon', function () {
    return view('coomingsoon');
})->name('cooming');

Route::get('/home', function () {
    Session::put('menu', 'home');
    return redirect('/dashboard/home');
});

Route::webhooks('webhook-moota-url');

Route::name('dashboard.')->prefix('dashboard')->middleware(['auth'])->group(function () {
    Route::get('/home', function () {
        return view('page.dashboard.index');
    });
    Route::name('dev.')->prefix('dev')->middleware(['role:Dev'])->group(function () {
        //mutasi
        Route::get('/mutasi', [DevMutationController::class, 'index'])->name('mutasi.index');
        Route::post('/mutasi/cek', [DevMutationController::class, 'find'])->name('mutasi.index.find');
        Route::post('/mutasi/usercek', [DevMutationController::class, 'usercek'])->name('mutasi.index.usercek');
        Route::post('/mutasi/store', [DevMutationController::class, 'store'])->name('mutasi.index.store');
        Route::get('/mutasi/history', [DevMutationController::class, 'history'])->name('mutasi.index.history');

        //activation Account
        Route::get('/activation-account', [DevActivationaccountController::class, 'index'])->name('activation-account.index');
        Route::get('/activation-account/approval', [DevActivationaccountController::class, 'approval'])->name('activation-account.approval');
        Route::get('/activation-account/approve{id}', [DevActivationaccountController::class, 'approve'])->name('activation-account.approve');

        //user
        Route::get('/user', [DevUserController::class, 'index'])->name('user.index');
        Route::get('/user/create', [DevUserController::class, 'create'])->name('user.create');
        Route::post('/user/store', [DevUserController::class, 'store'])->name('user.store');
        Route::post('/user/update', [DevUserController::class, 'update'])->name('user.update');
        Route::get('/user/delete{id}', [DevUserController::class, 'destroy'])->name('user.delete');
        Route::post('/user/profil', [DevUserController::class, 'profil'])->name('user.profil');
        Route::post('/user/password', [DevUserController::class, 'password'])->name('user.password');
        //member
        Route::get('/member', [DevMemberController::class, 'index'])->name('member.index');;
        Route::post('/member/store', [DevMemberController::class, 'store'])->name('member.store');
        Route::post('/member/update', [DevMemberController::class, 'update'])->name('member.update');
        Route::get('/member/delete{id}', [DevMemberController::class, 'destroy'])->name('member.delete');
        //akunMT5
        Route::get('/akunmt5', [DevAkunMT5Controller::class, 'index'])->name('akunmt5.index');
        Route::post('/akunmt5/store', [DevAkunMT5Controller::class, 'store'])->name('akunmt5.store');
        Route::post('/akunmt5/update', [DevAkunMT5Controller::class, 'update'])->name('akunmt5.update');
        //Bank
        Route::get('/bank', [DevBankController::class, 'index'])->name('bank.index');
        Route::post('/bank/store', [DevBankController::class, 'store'])->name('bank.store');
        Route::post('/bank/update', [DevBankController::class, 'update'])->name('bank.update');
        Route::get('/bank/delete{id}', [DevBankController::class, 'destroy'])->name('bank.delete');

        //level
        Route::get('/level', [DevLevelController::class, 'index'])->name('level.index');
        Route::post('/level/store', [DevLevelController::class, 'store'])->name('level.store');
        Route::post('/level/update', [DevLevelController::class, 'update'])->name('level.update');
        Route::get('/level/delete{id}', [DevLevelController::class, 'destroy'])->name('level.delete');
        //level
        Route::get('/robot', [DevRobotController::class, 'index'])->name('robot.index');
        Route::post('/robot/store', [DevRobotController::class, 'store'])->name('robot.store');
        Route::post('/robot/update', [DevRobotController::class, 'update'])->name('robot.update');
        Route::get('/robot/delete{id}', [DevRobotController::class, 'destroy'])->name('robot.delete');

        //Kurs
        Route::get('/kurs', [DevKursController::class, 'index'])->name('kurs.index');
        Route::post('/kurs/store', [DevKursController::class, 'store'])->name('kurs.store');
        Route::post('/kurs/update', [DevKursController::class, 'update'])->name('kurs.update');
        Route::get('/kurs/delete{id}', [DevKursController::class, 'destroy'])->name('kurs.delete');

        //Contact
        Route::post('/contact/update', [DevContactController::class, 'update'])->name('contact.update');
        Route::get('/contact', [DevContactController::class, 'index'])->name('contact.index');

        //Topup
        Route::get('/topup', [DevTopupController::class, 'index'])->name('topup.index');
        Route::get('/topup/approval', [DevTopupController::class, 'approval'])->name('topup.approval');
        Route::post('/topup/approve', [DevTopupController::class, 'approve'])->name('topup.approve');
        Route::get('/topupmt5/', [DevTopupController::class, 'indexmt5'])->name('topupmt5.index');
        Route::post('/topupmt5/tambah', [DevTopupController::class, 'tambah'])->name('topupmt5.tambah');
        Route::post('/topupmt5/tambahmodal', [DevTopupController::class, 'tambahmodal'])->name('topupmt5.tambahmodal');
        // Route::get('/topupmt5/kurang', [DevTopupController::class, 'tambah'])->name('topup.approve');
        // Route::post('/topupmt5/kurang{id}', [DevTopupController::class, 'approve'])->name('topup.approve');

        //WD
        Route::get('/withdraw', [DevWithdrawController::class, 'index'])->name('withdraw.index');
        Route::get('/withdraw/approval', [DevWithdrawController::class, 'approval'])->name('withdraw.approval');
        Route::post('/withdraw/approve', [DevWithdrawController::class, 'approve'])->name('withdraw.approve');

        //u=member bank
        Route::get('/member-bank', [DevMemberBankController::class, 'index'])->name('member-bank.index');
        Route::post('/member-bank/store', [DevMemberBankController::class, 'store'])->name('member-bank.store');
        Route::post('/member-bank/update', [DevMemberBankController::class, 'update'])->name('member-bank.update');
        Route::get('/member-bank/delete{id}', [DevMemberBankController::class, 'destroy'])->name('member-bank.delete');

        //version app
        Route::get('version-app', [DevVersionController::class, 'index'])->name('version.index');
        Route::post('version-app', [DevVersionController::class, 'store'])->name('version.store');

        //bypass robot
        Route::get('bypassrobot', [DevBypassController::class, 'index'])->name('bypassrobot.index');

        //networkt
        Route::get('network', [DevNetworkController::class, 'index'])->name('network.index');

        //keuntungan MT5

        Route::resources([
            'keuntungan' => DevKeuntunganController::class,
        ]);

app/Http/Controllers/Dev/ActivationaccountController.php
<?php

namespace App\Http\Controllers\Dev;

use App\Http\Controllers\Controller;
use App\Models\Activationaccount;
use Illuminate\Http\Request;
use App\Jobs\ReferralJobs;
use Illuminate\Support\Facades\Http;
use DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Carbon;
use Illuminate\Support\Str;

use function App\Helper\ReferralHelper\bonuscek;
use function App\Helper\ReferralHelper\cek;
use function App\Helper\ReferralHelper\cektotalbawah;

use Session;

class ActivationaccountController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $datas = DB::table('activation_accounts')
            ->select('activation_accounts.*', 'status.name as nama_status', 'users.name as nama_user', 'tabel_banks.bank_name as nama_bank')
            ->join('status', 'status.id', '=', 'activation_accounts.status')
            ->join('users', 'activation_accounts.user_id', '=', 'users.id')
            ->join('tabel_banks', 'tabel_banks.id', '=', 'activation_accounts.bank_id')
            ->where('activation_accounts.status', 5)
            ->where('activation_accounts.deleted_at', null)
            ->orderBy('activation_accounts.created_at', 'DESC')
            ->get();

        Session::put('menu', 'activation');
        Session::put('sub', 'activated');
        return view('page.dashboard.dev.activationaccount.index', compact('datas'));
    }

    public function approval()
    {
        $datas = DB::table('activation_accounts')
            ->select('activation_accounts.*', 'status.name as nama_status', 'users.name as nama_user', 'tabel_banks.bank_name as nama_bank', 'images.image_url as gambar')
            ->join('status', 'status.id', '=', 'activation_accounts.status')
            ->join('users', 'activation_accounts.user_id', '=', 'users.id')
            ->join('images', 'activation_accounts.image_id', '=', 'images.id')
            ->join('tabel_banks', 'tabel_banks.id', '=', 'activation_accounts.bank_id')
            ->where('activation_accounts.status', 4)
            ->where('activation_accounts.deleted_at', null)
            ->orderBy('activation_accounts.created_at', 'DESC')
            ->get();

        Session::put('menu', 'activation');
        Session::put('sub', 'approval');
        return view('page.dashboard.dev.activationaccount.approval', compact('datas'));
    }

    public function approve($id)
    {

        DB::table('activation_accounts')->where('id', $id)->update([
            'status' => 5,
            'updated_at' => Carbon::now()
        ]);

        $getuserid = DB::select("select * from activation_accounts where id='$id'");
        foreach ($getuserid as $key) {
            $getrobot = DB::select("select * from users where id='$key->user_id'");
            foreach ($getrobot as $keyy) {
                DB::table('users')->where('id', $key->user_id)->update([
                    'status' => 3,
                    'email_verified_at' => Carbon::now(),
                    'total_robot' => $keyy->total_robot + 1
                ]);
            }
        }

        cek($getuserid[0]->user_id);
        cektotalbawah($getuserid[0]->user_id);


        return redirect()->route('dashboard.dev.activation-account.approval')->with('berhasilapprove', '.');;
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Activationaccount::where('id', $id)->update([
            'status' => 5,
        ]);

        cek($id);

        return redirect()->route('dashboard.dev.activation-account.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Dev/AkunMT5Controller.php
<?php

namespace App\Http\Controllers\Dev;

use App\Http\Controllers\Controller;
use App\Models\Accountmt5;
use App\Models\User;
use Illuminate\Auth\Events\Validated;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;
use DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Carbon;
use Session;

class AkunMT5Controller extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $datas = Accountmt5::with(['user'])->get();
        // dd($datas);
        // return json($datas);

        Session::put('menu','manajemenuser');
        Session::put('sub','akunmt5');
        return view('page.dashboard.dev.akunmt5.index', compact(['datas']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     *

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Accountmt5::create([
            'user_id' => $request->input('user_id'),
            'username' => $request->input('username'),
            'password' => $request->input('password'),
            'password_investor' => $request->input('passwordinv'),
            'server' => $request->input('server'),
            'ip_server' => $request->input('server_ip'),
            'created_at' => Carbon::now(),
        ]);
        return redirect()->route('dashboard.dev.akunmt5.index')->with('berhasil', '.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        Accountmt5::where('id', $request->input('id'))->update([
            'username' => $request->input('username'),
            'password' => $request->input('passwordedit'.$request->id),
            'password_investor' => $request->input('passwordinvedit'.$request->id),
            'server' => $request->input('server'),
            'ip_server' => $request->input('server_ip'),
            'updated_at' => Carbon::now(),
        ]);
        return redirect()->route('dashboard.dev.akunmt5.index')->with('berhasilupdate', '.');
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/page/dashboard/dev/member-bank/index.blade.php
@extends('layouts.dash')
<title>Dashboard | Master Data</title>
@section('content')
     <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
        Master Data
        <!-- <small>advanced tables</small> -->
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li><a href="#">Master Data</a></li>
        <li class="active">Member Bank</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      @php if(Session::get('berhasil')){ @endphp 
      <div class="alert alert-success" >
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
                     Data Berhasil ditambahkan
      </div> @php } @endphp
      @php if(Session::get('berhasilupdate')){ @endphp 
      <div class="alert alert-warning" >
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
                     Data Berhasil diupdate
      </div> @php } @endphp
      @php if(Session::get('hapus')){ @endphp 
      <div class="alert alert-danger" >
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
                     Data Berhasil dihapus
      </div> @php } @endphp
      <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">Data Bank Member</h3>
              <span class="input-group-btn">
                <a data-toggle="modal" data-target="#modal-tambah"><buttonid="search-btn" class="btn btn-primary"><i class="fa fa-plus"></i>
                </button>Tambah Data</a>
              </span>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="table1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>#</th>
                  <th>Bank</th>
                  <th>Kode</th>
                  <th>Member</th>
                  <th>Nama Akun</th>
                  <th>No. Rekening</th>
                  <th>Action</th>
                </tr>
                </thead>
                <tbody>
                @php
                    $i = 1 ;
                @endphp 
                @foreach ($datas as $dt)
                <tr>
                  <td>{{$i++}}</td>
                  <td>{{$dt->bank->nama_bank}}</td>
                  <td>{{$dt->bank->kode_bank}}</td>
                  <td>{{$dt->user->name}}</td>
                  <td>{{$dt->account_name}}</td>
                  <td>{{$dt->bank_rek}}</td>
                  <td><a class="btn btn-warning" data-toggle="modal" data-target="#modal-edit{{$dt->id}}"><i class="fa fa-pencil"></i>
                      </a> 
                      <a href="/dashboard/dev/member-bank/delete{{$dt->id}}" class="btn btn-danger" onclick="return(confirm('Apakah Data ini Akan dihapus?'));"><i class="fa fa-trash"></i>
                      </a> 
                  </td>
                </tr>
                @endforeach
                </tbody>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->


@foreach ($datas as $dt)
<div class="modal fade" id="modal-edit{{$dt->id}}" role="dialog">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title">Edit Bank {{$dt->nama_user}}</h4>
            </div>
            <div class="modal-body">
             <form class="form-horizontal" action="{{ route('dashboard.dev.member-bank.update') }}" method="post">
            @csrf
              <div class="box-body">
                <div class="form-group">
                  <input type="hidden" class="form-control" id="id" placeholder="Michael Sumadi" name="id" required="" value="{{$dt->id}}">
                  <label for="bank_id" class="col-sm-2 control-label">Bank</label>
                  <div class="col-sm-10">
                    @php
                    $data = DB::select("select * from bank_kodes");
                    @endphp
                    <select class="form-control" name="bank_id" id="bank_id">
                      @foreach ($data as $dta)
                      <option value="{{$dta->id}}">{{$dta->nama_bank}}</option>
                      @endforeach
                    </select>
                  </div>
                </div>
                <div class="form-group">
                  <label for="nama_akun" class="col-sm-2 control-label">Nama Akun</label>
                  <div class="col-sm-10">
                    <input type="text" class="form-control" id="nama_akun" placeholder="Michael Sumadi" name="nama_akun" required="" value="{{$dt->account_name}}">
                  </div>
                </div>
               <div class="form-group">
                  <label for="no_rek" class="col-sm-2 control-label">No. Rekening</label>
                  <div class="col-sm-10">
                    <input type="number" class="form-control" id="no_rek" placeholder=000123000222" name="no_rek" required="" value="{{$dt->bank_rek}}">
                  </div>
                </div>
              </div>
              <!-- /.box-body -->
              <div class="box-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Batal</button>
                <button type="submit" class="btn btn-primary">Simpan</button>
              </div>
              <!-- /.box-footer -->
            </form>
            </div>
          </div>
          <!-- /.modal-content -->
        </div>
      </div>
@endforeach
<div class="modal fade" id="modal-tambah" role="dialog">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title">Tambah Bank</h4>
            </div>
            <div class="modal-body">
             <form class="form-horizontal" action="{{ route('dashboard.dev.member-bank.store') }}" method="post">
            @csrf
              <div class="box-body">
                <div class="form-group">
                  <label for="user_id" class="col-sm-2 control-label">Member</label>
                  <div class="col-sm-10">
                    @php
                    $data = DB::select("select * from users");
                    @endphp
                    <!-- <select class="form-control" name="user_id" id="user_id">
                      @foreach ($data as $dt)
                      <option value="{{$dt->id}}">{{$dt->name}}</option>
                      @endforeach
                    </select> -->
                    <select class="form-control select2" name="user_id" id="user_id" style="width: 100%;">
                      <!-- <option selected="selected">Alabama</option> -->
                      @foreach ($data as $dt)
                      <option value="{{$dt->id}}">{{$dt->name}}</option>
                      @endforeach
                    </select>
                  </div> 
                  
                </div>
                <div class="form-group">
                  <label for="bank_id" class="col-sm-2 control-label">Bank</label>
                  <div class="col-sm-10">
                    @php
                    $data = DB::select("select * from bank_kodes");
                    @endphp
                    <select class="form-control" name="bank_id" id="bank_id">
                      @foreach ($data as $dt)
                      <option value="{{$dt->id}}">{{$dt->nama_bank}}</option>
                      @endforeach
                    </select>
                  </div>
                </div>
                <div class="form-group">
                  <label for="nama_akun" class="col-sm-2 control-label">Nama Akun</label>
                  <div class="col-sm-10">
                    <input type="text" class="form-control" id="nama_akun" placeholder="Michael Sumadi" name="nama_akun" required="" >
                  </div>
                </div>
               <div class="form-group">
                  <label for="no_rek" class="col-sm-2 control-label">No. Rekening</label>
                  <div class="col-sm-10">
                    <input type="number" class="form-control" id="no_rek" placeholder=000123000222" name="no_rek" required="" >
                  </div>
                </div>
              </div>
              <!-- /.box-body -->
              <div class="box-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Batal</button>
                <button type="submit" class="btn btn-primary">Simpan</button>
              </div>
              <!-- /.box-footer -->
            </form>
            </div>
          </div>
          <!-- /.modal-content -->
        </div>

    </section>
    <!-- /.content -->
    <!-- DataTables -->

@endsection
@section('scripts')
    <script src="{{asset('assets/AdminLTE/bower_components/datatables.net/js/jquery.dataTables.min.js')}}"></script>

    <script src="{{asset('assets/AdminLTE/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>

    <script>
        $(function () {
        //Initialize Select2 Elements
        $('.select2').select2()
        })
    </script>
    <script>
      //Initialize Select2 Elements
      
      $(function () {
        $('#table1').DataTable({
          'paging'      : true,
          'lengthChange': true,
          'searching'   : true,
          'ordering'    : true,
          'info'        : true,
          'autoWidth'   : true
        })
        $('#table2').DataTable({
          'paging'      : true,
          'lengthChange': true,
          'searching'   : true,
          'ordering'    : true,
          'info'        : true,
          'autoWidth'   : true
        })
      })
    </script>
 

<!-- Select2 -->
<script src="{{asset('assets/AdminLTE/bower_components/select2/dist/js/select2.full.min.js')}}"></script>

@endsection