routes/web.php
<?php

use App\Http\Controllers\customer\RobotController;
use App\Http\Controllers\Dev\MutationController as DevMutationController;
use App\Http\Controllers\Dev\UserController as DevUserController;
use App\Http\Controllers\Dev\BankController as DevBankController;
use App\Http\Controllers\Dev\LevelController as DevLevelController;
use App\Http\Controllers\Dev\RobotController as DevRobotController;
use App\Http\Controllers\Dev\KursController as DevKursController;
use App\Http\Controllers\Dev\ContactController as DevContactController;
use App\Http\Controllers\Dev\TopupController as DevTopupController;
use App\Http\Controllers\Dev\MemberBankController as DevMemberBankController;
use App\Http\Controllers\Dev\MemberController as DevMemberController;
use App\Http\Controllers\Dev\AkunMT5Controller as DevAkunMT5Controller;
use App\Http\Controllers\Dev\WithdrawController as DevWithdrawController;
use App\Http\Controllers\Dev\ActivationaccountController as DevActivationaccountController;
use App\Http\Controllers\Dev\versionapp\VersionController as DevVersionController;
use App\Http\Controllers\Dev\BypassController as DevBypassController;
use App\Http\Controllers\Dev\NetworkController as DevNetworkController;
use App\Http\Controllers\Dev\KeuntunganController as DevKeuntunganController;
//Customer
use App\Http\Controllers\Customer\robot\RobotController as CustomerRobotController;
use App\Http\Controllers\Customer\robot\BeliRobotController as CustomerBeliRobotController;
use App\Http\Controllers\Customer\profile\ProfileController as CustomerProfileController;

//cashier
use App\Http\Controllers\Cashier\masterdata\UserController as CashierUserController;
use App\Http\Controllers\Cashier\topup\TopupController as CashierTopupController;
use App\Http\Controllers\Cashier\WithdrawController as CashierWithdrawController;
use App\Http\Controllers\Cashier\keuntungan\KeuntunganController as CashierKeuntunganController;
use App\Http\Controllers\Cashier\manajemenuser\AkunMT5Controller as CashierAkunMT5Controller;
use App\Http\Controllers\Cashier\ActivationaccountController as CashierActivationaccountController;
use App\Http\Controllers\Cashier\TopupController as CashierTopup2Controller;
use App\Http\Controllers\Cashier\mutasi\MutasiController as CashierMutasiController;
use App\Http\Controllers\Dev\TRC20\TRC20Controller;
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
})->middleware(['guest']);


Route::get('/csrf', function () {
    return csrf_token();
});


Route::get('/coomingsoon', function () {
    return view('coomingsoon');
})->name('cooming');

Route::get('/home', function () {
    Session::put('menu', 'home');
    return redirect('/dashboard/home');
});

Route::webhooks('webhook-moota-url');

Route::name('dashboard.')->prefix('dashboard')->middleware(['auth'])->group(function () {
    Route::get('/home', function () {
        return view('page.dashboard.index');
    });
    Route::name('dev.')->prefix('dev')->middleware(['role:Dev'])->group(function () {
        //mutasi
        Route::get('/mutasi', [DevMutationController::class, 'index'])->name('mutasi.index');
        Route::post('/mutasi/cek', [DevMutationController::class, 'find'])->name('mutasi.index.find');
        Route::post('/mutasi/usercek', [DevMutationController::class, 'usercek'])->name('mutasi.index.usercek');
        Route::post('/mutasi/store', [DevMutationController::class, 'store'])->name('mutasi.index.store');
        Route::get('/mutasi/history', [DevMutationController::class, 'history'])->name('mutasi.index.history');

        //activation Account
        Route::get('/activation-account', [DevActivationaccountController::class, 'index'])->name('activation-account.index');
        Route::get('/activation-account/approval', [DevActivationaccountController::class, 'approval'])->name('activation-account.approval');
        Route::get('/activation-account/approve{id}', [DevActivationaccountController::class, 'approve'])->name('activation-account.approve');

        //user
        Route::get('/user', [DevUserController::class, 'index'])->name('user.index');
        Route::get('/user/create', [DevUserController::class, 'create'])->name('user.create');
        Route::post('/user/store', [DevUserController::class, 'store'])->name('user.store');
        Route::post('/user/update', [DevUserController::class, 'update'])->name('user.update');
        Route::get('/user/delete{id}', [DevUserController::class, 'destroy'])->name('user.delete');
        Route::post('/user/profil', [DevUserController::class, 'profil'])->name('user.profil');
        Route::post('/user/password', [DevUserController::class, 'password'])->name('user.password');
        //member
        Route::get('/member', [DevMemberController::class, 'index'])->name('member.index');;
        Route::post('/member/store', [DevMemberController::class, 'store'])->name('member.store');
        Route::post('/member/update', [DevMemberController::class, 'update'])->name('member.update');
        Route::get('/member/delete{id}', [DevMemberController::class, 'destroy'])->name('member.delete');
        //akunMT5
        Route::get('/akunmt5', [DevAkunMT5Controller::class, 'index'])->name('akunmt5.index');
        Route::post('/akunmt5/store', [DevAkunMT5Controller::class, 'store'])->name('akunmt5.store');
        Route::post('/akunmt5/update', [DevAkunMT5Controller::class, 'update'])->name('akunmt5.update');
        //Bank
        Route::get('/bank', [DevBankController::class, 'index'])->name('bank.index');
        Route::post('/bank/store', [DevBankController::class, 'store'])->name('bank.store');
        Route::post('/bank/update', [DevBankController::class, 'update'])->name('bank.update');
        Route::get('/bank/delete{id}', [DevBankController::class, 'destroy'])->name('bank.delete');

        //level
        Route::get('/level', [DevLevelController::class, 'index'])->name('level.index');
        Route::post('/level/store', [DevLevelController::class, 'store'])->name('level.store');
        Route::post('/level/update', [DevLevelController::class, 'update'])->name('level.update');
        Route::get('/level/delete{id}', [DevLevelController::class, 'destroy'])->name('level.delete');
        //level
        Route::get('/robot', [DevRobotController::class, 'index'])->name('robot.index');
        Route::post('/robot/store', [DevRobotController::class, 'store'])->name('robot.store');
        Route::post('/robot/update', [DevRobotController::class, 'update'])->name('robot.update');
        Route::get('/robot/delete{id}', [DevRobotController::class, 'destroy'])->name('robot.delete');

        //Kurs
        Route::get('/kurs', [DevKursController::class, 'index'])->name('kurs.index');
        Route::post('/kurs/store', [DevKursController::class, 'store'])->name('kurs.store');
        Route::post('/kurs/update', [DevKursController::class, 'update'])->name('kurs.update');
        Route::get('/kurs/delete{id}', [DevKursController::class, 'destroy'])->name('kurs.delete');

        //Contact
        Route::post('/contact/update', [DevContactController::class, 'update'])->name('contact.update');
        Route::get('/contact', [DevContactController::class, 'index'])->name('contact.index');

        //Topup
        Route::get('/topup', [DevTopupController::class, 'index'])->name('topup.index');
        Route::get('/topup/approval', [DevTopupController::class, 'approval'])->name('topup.approval');
        Route::post('/topup/approve', [DevTopupController::class, 'approve'])->name('topup.approve');
        Route::get('/topupmt5/', [DevTopupController::class, 'indexmt5'])->name('topupmt5.index');
        Route::post('/topupmt5/tambah', [DevTopupController::class, 'tambah'])->name('topupmt5.tambah');
        Route::post('/topupmt5/tambahmodal', [DevTopupController::class, 'tambahmodal'])->name('topupmt5.tambahmodal');
        // Route::get('/topupmt5/kurang', [DevTopupController::class, 'tambah'])->name('topup.approve');
        // Route::post('/topupmt5/kurang{id}', [DevTopupController::class, 'approve'])->name('topup.approve');

        //WD
        Route::get('/withdraw', [DevWithdrawController::class, 'index'])->name('withdraw.index');
        Route::get('/withdraw/approval', [DevWithdrawController::class, 'approval'])->name('withdraw.approval');
        Route::post('/withdraw/approve', [DevWithdrawController::class, 'approve'])->name('withdraw.approve');

        //u=member bank
        Route::get('/member-bank', [DevMemberBankController::class, 'index'])->name('member-bank.index');
        Route::post('/member-bank/store', [DevMemberBankController::class, 'store'])->name('member-bank.store');
        Route::post('/member-bank/update', [DevMemberBankController::class, 'update'])->name('member-bank.update');
        Route::get('/member-bank/delete{id}', [DevMemberBankController::class, 'destroy'])->name('member-bank.delete');

        //version app
        Route::get('version-app', [DevVersionController::class, 'index'])->name('version.index');
        Route::post('version-app', [DevVersionController::class, 'store'])->name('version.store');

        //bypass robot
        Route::get('bypassrobot', [DevBypassController::class, 'index'])->name('bypassrobot.index');

        //networkt
        Route::get('network', [DevNetworkController::class, 'index'])->name('network.index');

        //keuntungan MT5

        Route::resources([
            'keuntungan' => DevKeuntunganController::class,
        ]);

app/Http/Controllers/Cashier/ActivationaccountController.php
<?php

namespace App\Http\Controllers\Cashier;

use App\Http\Controllers\Controller;
use App\Models\Activationaccount;
use Illuminate\Http\Request;
use App\Jobs\ReferralJobs;
use Illuminate\Support\Facades\Http;
use DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Carbon;
use Illuminate\Support\Str;

use function App\Helper\ReferralHelper\bonuscek;
use function App\Helper\ReferralHelper\cek;
use Session;

class ActivationaccountController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $datas = DB::table('activation_accounts')
            ->select('activation_accounts.*', 'status.name as nama_status', 'users.name as nama_user', 'tabel_banks.bank_name as nama_bank')
            ->join('status', 'status.id', '=', 'activation_accounts.status')
            ->join('users', 'activation_accounts.user_id', '=', 'users.id')
            ->join('tabel_banks', 'tabel_banks.id', '=', 'activation_accounts.bank_id')
            ->where('activation_accounts.status', 5)
            ->where('activation_accounts.deleted_at', null)
            ->orderBy('activation_accounts.created_at', 'DESC')
            ->get();

        Session::put('menu', 'activation');
        Session::put('sub', 'activated');
        return view('page.dashboard.cashier.activationaccount.index', compact('datas'));
    }

    public function approval()
    {
        $datas = DB::table('activation_accounts')
            ->select('activation_accounts.*', 'status.name as nama_status', 'users.name as nama_user', 'tabel_banks.bank_name as nama_bank', 'images.image_url as gambar')
            ->join('status', 'status.id', '=', 'activation_accounts.status')
            ->join('users', 'activation_accounts.user_id', '=', 'users.id')
            ->join('images', 'activation_accounts.image_id', '=', 'images.id')
            ->join('tabel_banks', 'tabel_banks.id', '=', 'activation_accounts.bank_id')
            ->where('activation_accounts.status', 4)
            ->where('activation_accounts.deleted_at', null)
            ->orderBy('activation_accounts.created_at', 'DESC')
            ->get();

        Session::put('menu', 'activation');
        Session::put('sub', 'approval');
        return view('page.dashboard.cashier.activationaccount.approval', compact('datas'));
    }

    public function approve($id)
    {

        DB::table('activation_accounts')->where('id', $id)->update([
            'status' => 5,
            'updated_at' => Carbon::now()
        ]);

        $getuserid = DB::select("select * from activation_accounts where id='$id'");
        foreach ($getuserid as $key) {
            $getrobot = DB::select("select * from users where id='$key->user_id'");
            foreach ($getrobot as $keyy) {
                DB::table('users')->where('id', $key->user_id)->update([
                    'status' => 3,
                    'email_verified_at' => Carbon::now(),
                    'total_robot' => $keyy->total_robot + 1
                ]);
            }
        }

        // dd($getuserid[0]->user_id);
        cek($getuserid[0]->user_id);

        return redirect()->route('dashboard.cashier.activation-account.approval')->with('berhasilapprove', '.');;
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Activationaccount::where('id', $id)->update([
            'status' => 5,
        ]);

        cek($id);

        return redirect()->route('dashboard.cashier.activation-account.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Cashier/UserController.php
<?php

namespace App\Http\Controllers\Cashier;

use App\Http\Controllers\Controller;
use App\Models\Downline;
use App\Models\Upline;
use App\Models\User;
use Illuminate\Http\Request;

use function App\Helper\ReferralHelper\cekminusrobot;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = User::find($id);
        Downline::where('downline_id', $id)->delete();
        Upline::where('user_id', $id)->delete();
        $data->delete();

        cekminusrobot($id);
    }
}

resources/views/page/dashboard/cashier/mutasi/create.blade.php
@extends('layouts.dash',['title'=>'Dailypips - Dashboard'])

@section('script-top')
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{ asset('assets/AdminLTE/plugins/fontawesome-free/css/all.min.css') }}">
    <!-- Theme style -->
    <link rel="stylesheet" href="../../dist/css/adminlte.min.css">
@endsection

@section('script-bottom')
    <!-- jQuery -->
    <script src="../../plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- bs-custom-file-input -->
    <script src="../../plugins/bs-custom-file-input/bs-custom-file-input.min.js"></script>
    <!-- AdminLTE App -->
    <script src="../../dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="../../dist/js/demo.js"></script>
    <!-- Page specific script -->
    <script>
        $(function() {
            bsCustomFileInput.init();
        });
    </script>
@endsection
@section('content')
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-6">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Checking Mutattion</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->

                        <form action="{{ route('dashboard.cashier.mutasi.index.find') }}" method="post">
                            @csrf
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Amount</label>
                                    <input name="amount" type="text" class="form-control" placeholder="Amount" required>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Description</label>
                                    <input name="description" type="text" class="form-control" placeholder="Description">
                                </div>
                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.card -->

                </div>

            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection

resources/views/page/dashboard/cashier/mutasi/detail.blade.php
@extends('layouts.dash',['title'=>'cek mutasi user'])

@section('content')
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-6">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Quick Example</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form method="POST" action="{{ route('dashboard.cashier.mutasi.index.store') }}">
                            @csrf
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Email address</label>
                                    <select class="custom-select form-control-border" id="exampleSelectBorder"
                                        name="user_id">
                                        @foreach ($data as $item)
                                            <option value="{{ $item->id }}">Email:{{ $item->email }}
                                                Name:{{ $item->name }}
                                            </option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="card-body">
                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Email address</label>
                                        <input type="text" class="form-control" name="account_number"
                                            value="{{ $datamoota['account_number'] }}" readonly>
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputPassword1">Password</label>
                                        <input type="text" class="form-control" name="date"
                                            value="{{ $datamoota['date'] }}" readonly>
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputPassword1">Password</label>
                                        <input type="text" class="form-control" name="description"
                                            value="{{ $datamoota['description'] }}" readonly>
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputPassword1">Password</label>
                                        <input type="text" class="form-control" name="amount"
                                            value="{{ $datamoota['amount'] }}" readonly>
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputPassword1">Password</label>
                                        <input type="text" class="form-control" name="type"
                                            value="{{ $datamoota['type'] }}" readonly>
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputPassword1">Password</label>
                                        <input type="text" class="form-control" name="note"
                                            value="{{ $datamoota['note'] }}" readonly>
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputPassword1">Password</label>
                                        <input type="text" class="form-control" name="balance"
                                            value="{{ $datamoota['balance'] }}" readonly>
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputPassword1">Password</label>
                                        <input type="text" class="form-control" name="created_at"
                                            value="{{ $datamoota['created_at'] }}" readonly>
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputPassword1">Password</label>
                                        <input type="text" class="form-control" name="updated_at"
                                            value="{{ $datamoota['updated_at'] }}" readonly>
                                    </div>
                                </div>
                                <!-- /.card-body -->

                                <div class="card-footer">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </div>
                        </form>
                    </div>
                    <!-- /.card -->

                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection

resources/views/page/dashboard/cashier/mutasi/index.blade.php
@extends('layouts.dash',['title'=>'user_index'])

@section('content')
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">

                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">DataTable with default features</h3>
                        </div>
                        <!-- /.card-header -->
                        <a href="{{ route('dashboard.cashier.mutasi.index') }}"><button type="button"
                                class="btn btn-primary">Back</button></a>
                        <div class="card-body">
                            <table id="example1" class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th>account_number</th>
                                        <th>date</th>
                                        <th>description</th>
                                        <th>amount</th>
                                        <th>type</th>
                                        <th>note</th>
                                        <th>balance</th>
                                        <th>created_at</th>
                                        <th>updated_at</th>
                                        <th>action</th>
                                    </tr>
                                </thead>
                                @foreach ($datas as $item)
                                    <tbody>
                                        <td>{{ $item->account_number }}</td>
                                        <td>{{ $item->date }}</td>
                                        <td>{{ $item->description }}</td>
                                        <td>{{ $item->amount }}</td>
                                        <td>{{ $item->type }}</td>
                                        <td>{{ $item->note }}</td>
                                        <td>{{ $item->balance }}</td>
                                        <td>{{ $item->created_at }}</td>
                                        <td>{{ $item->updated_at }}</td>
                                        <td>
                                            <form action="{{ route('dashboard.dev.mutasi.index.usercek') }}"
                                                method="post">
                                                @csrf
                                                <input type="hidden" name="account_number"
                                                    value="{{ $item->account_number }}">
                                                <input type="hidden" name="date" value="{{ $item->date }}">
                                                <input type="hidden" name="description" value="{{ $item->description }}">
                                                <input type="hidden" name="amount" value="{{ $item->amount }}">
                                                <input type="hidden" name="type" value="{{ $item->type }}">
                                                <input type="hidden" name="note" value="{{ $item->note }}">
                                                <input type="hidden" name="balance" value="{{ $item->balance }}">
                                                <input type="hidden" name="created_at" value="{{ $item->created_at }}">
                                                <input type="hidden" name="updated_at" value="{{ $item->updated_at }}">
                                                <button type="submit" class="btn btn-success">Aprove</button>
                                            </form>
                                        </td>
                                    </tbody>
                                @endforeach
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- /.content -->

@endsection